# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experts', '0002_auto_20180503_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ('popularity',)},
        ),
        migrations.AddField(
            model_name='expert',
            name='deleted',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
